=== LennartPNL/XML-Eindopdracht/garages.dtd
<?xml version="1.0" encoding="utf-8"?>

<!ENTITY % car "(kenteken, type, merk, model, bouwjaar, brandstof, prijs, datumEindAPK, fotos)">
<!ENTITY % newcar "(kenteken?, type, merk, model, bouwjaar, brandstof, prijs, datumEindAPK?, fotos)">
<!ENTITY % openingsTijden "open CDATA #REQUIRED 
  												sluiting CDATA #REQUIRED">
<!-- ROOT -->
<!ELEMENT garages (garage+)>

<!-- GARAGE -->
<!ATTLIST garage naam CDATA #REQUIRED>
<!ELEMENT garage (adres, contactGegevens, faciliteiten, fotos, werkplaats, showroom, keurmerken, medewerkers)>

<!ELEMENT openingstijden (maandag, dinsdag, woensdag, donderdag, vrijdag, zaterdag, zondag)>
<!ELEMENT maandag EMPTY>
<!ELEMENT dinsdag EMPTY>
<!ELEMENT woensdag EMPTY>
<!ELEMENT donderdag EMPTY>
<!ELEMENT vrijdag EMPTY>
<!ELEMENT zaterdag EMPTY>
<!ELEMENT zondag EMPTY>
<!ATTLIST maandag %openingsTijden;>
<!ATTLIST dinsdag %openingsTijden;>
<!ATTLIST woensdag %openingsTijden;>
<!ATTLIST donderdag %openingsTijden;>
<!ATTLIST vrijdag %openingsTijden;>
<!ATTLIST zaterdag %openingsTijden;>
<!ATTLIST zondag %openingsTijden;>

<!-- ADRES -->
<!ELEMENT adres (straat, nummer, postcode, plaats, provincie)>
<!ELEMENT straat (#PCDATA)>
<!ELEMENT nummer (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT plaats (#PCDATA)>
<!ELEMENT provincie (#PCDATA)>

<!-- CONTACTGEGEVENS -->
<!ELEMENT contactGegevens (telefoonnummer, email, website?, omschrijving, routebeschrijving)>
<!ELEMENT telefoonnummer (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT website (#PCDATA)>
<!ELEMENT omschrijving (#PCDATA)>
<!ELEMENT routebeschrijving (#PCDATA)>

<!-- FACILITEITEN -->
<!ELEMENT faciliteiten (pompen, wassen, winkel)>
<!ELEMENT pompen (pomp*)>
<!ELEMENT pomp (#PCDATA)>
<!ATTLIST pomp brandstofType (Benzine | Gas | Diesel) "Benzine">
<!ELEMENT wassen (wasstraat, wasbox)*>
<!ELEMENT wasstraat (#PCDATA)>
<!ELEMENT wasbox (#PCDATA)>
<!ATTLIST wasstraat aantal CDATA #REQUIRED>
<!ATTLIST wasbox aantal CDATA #REQUIRED>

<!-- FACILITEITEN: WINKEL -->
<!ELEMENT winkel (openingstijden, assortiment)>
<!ELEMENT assortiment (levensmiddelen?, rookwaar?, tijdschriften?, autoAccesoires?)>
<!ELEMENT levensmiddelen (#PCDATA)>
<!ELEMENT rookwaar (#PCDATA)>
<!ELEMENT tijdschriften (#PCDATA)>
<!ELEMENT autoAccesoires (#PCDATA)>

<!-- FOTOS -->
<!ELEMENT fotos (foto)+>
<!ELEMENT foto (bestandsLocatie, alt)>
<!ELEMENT alt (#PCDATA)>
<!ELEMENT bestandsLocatie (#PCDATA)>

<!-- WERKPLAATS -->
<!ELEMENT werkplaats (openingstijden, werkzaamheden)>
<!ELEMENT werkzaamheden (onderhoud, APKkeuring, schadeherstel, ruitenreparatie, aircoservice, bandenservice)?>
<!ELEMENT onderhoud EMPTY>
<!ELEMENT APKkeuring EMPTY>
<!ELEMENT schadeherstel EMPTY>
<!ELEMENT ruitenreparatie EMPTY>
<!ELEMENT aircoservice EMPTY>
<!ELEMENT bandenservice EMPTY>

<!-- SHOWROOM -->
<!ELEMENT showroom (openingstijden, autos)>
<!ELEMENT autos (nieuw*, occasions*, huur+)>
<!ELEMENT nieuw (%newcar;)>
<!ELEMENT occasions (%car;)>
<!ELEMENT huur (%car;)>
<!ATTLIST huur uitleenbaar (true | false) "false">
<!ELEMENT kenteken (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT merk (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT bouwjaar (#PCDATA)>
<!ELEMENT brandstof (#PCDATA)>
<!ATTLIST brandstof type (Benzine | Gas | Diesel | Geen) "Geen">
<!ELEMENT prijs (#PCDATA)>
<!ATTLIST prijs valuta (euro) "euro">
<!ELEMENT datumEindAPK (#PCDATA)>

<!-- KEURMERKEN -->
<!ELEMENT keurmerken (keurmerk*)>
<!ELEMENT keurmerk (#PCDATA)>
<!ATTLIST keurmerk type (RDW | BOVAG | Geen) "Geen">

<!-- MEDEWERKERS -->
<!ELEMENT medewerkers (medewerker)+>
<!ELEMENT medewerker (naam, foto, functie)>
<!ELEMENT naam (#PCDATA)>
<!ELEMENT functie (#PCDATA)>

=== LennartPNL/XML-Eindopdracht/24garages.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE garages SYSTEM "garages.dtd">


<garages>

    <garage naam="Het Schuurtje"> <!-- garage 1 -->

      <!--Adres-->
      <adres>
        <straat>Berendslaan</straat>
        <nummer>89</nummer>
        <postcode>7826UP</postcode>
        <plaats>Emmen</plaats>
        <provincie>Drenthe</provincie>
      </adres>

      <!--ContactGegevens-->
      <contactGegevens>
        <telefoonnummer>0591277359</telefoonnummer>
        <email>info@garageschuurman.nl</email>
        <website>http://www.garageschuurman.nl</website>
        <omschrijving> Edwin Schuurman beheert sinds 1974 garage Het Schuurtje.</omschrijving>
        <routebeschrijving> https://www.google.nl/maps/dir/''/garage+Het+Schuurtje/</routebeschrijving>
      </contactGegevens>

      <!--Faciliteiten-->
      	<faciliteiten>
            <pompen>
                <pomp brandstofType="Benzine"/>
            </pompen>

            <wassen>
                <wasstraat aantal="1"/>
                <wasbox aantal="2"/>
            </wassen>
          <!--Winkel-->
          	<winkel>

              <openingstijden>
                <maandag open="10:00" sluiting="21:00"/>
                <dinsdag open="10:00" sluiting="21:00"/>
                <woensdag open="10:00" sluiting="21:00"/>
                <donderdag open="10:00" sluiting="21:00"/>
                <vrijdag open="10:00" sluiting="21:00"/>
                <zaterdag open="10:00" sluiting="21:00"/>
                <zondag open="12:00" sluiting="18:00"/>
              </openingstijden>

              <assortiment>
                <levensmiddelen/>
                <rookwaar/>
                <tijdschriften/>
                <autoAccesoires/>
              </assortiment>

        		</winkel>
        </faciliteiten>

				<!--Foto's-->
        <fotos>
            <foto>
                <bestandsLocatie>http://www.garageschuurman.nl/foto.jpg</bestandsLocatie>
              <alt>Onze Garage</alt>
            </foto>
        </fotos>

				<!--Werkplaats-->
        <werkplaats>

          <openingstijden>
            <maandag open="13:00" sluiting="13:01"/>
            <dinsdag open="13:00" sluiting="13:01"/>
          	<woensdag open="13:00" sluiting="13:01"/>
          	<donderdag open="13:00" sluiting="13:01"/>
          	<vrijdag open="13:00" sluiting="13:01"/>
          	<zaterdag open="13:00" sluiting="13:01"/>
          	<zondag open="-" sluiting="-"/>
          </openingstijden>

          <werkzaamheden>
              <onderhoud/>
              <APKkeuring/>
              <schadeherstel/>
              <ruitenreparatie/>
              <aircoservice/>
              <bandenservice/>
          </werkzaamheden>
        </werkplaats>

				<!--Showroom-->
        <showroom>

          <openingstijden>
            <maandag open="13:00" sluiting="13:01"/>
            <dinsdag open="13:00" sluiting="13:01"/>
          	<woensdag open="13:00" sluiting="13:01"/>
          	<donderdag open="13:00" sluiting="13:01"/>
          	<vrijdag open="13:00" sluiting="13:01"/>
          	<zaterdag open="13:00" sluiting="13:01"/>
          	<zondag open="-" sluiting="-"/>
          </openingstijden>

          <autos>
              <nieuw>
                  <kenteken>BR-UX-14</kenteken>
                  <type>Hatchback</type>
                  <merk>Opel</merk>
                  <model>Astra</model>
                  <bouwjaar>1990</bouwjaar>
                  <brandstof>Benzine</brandstof>
                  <prijs valuta="euro">1499</prijs>
                  <datumEindAPK>12-11-1994</datumEindAPK>
                  <fotos>
                      <foto>
                          <bestandsLocatie>http://www.garageschuurman.nl/opelastra.jpg</bestandsLocatie>
                          <alt>Onze Auto</alt>
                      </foto>
                  </fotos>
              </nieuw>

              <!--Occasions-->
              <occasions>
                  <kenteken>UP-12-JA</kenteken>
                  <type>Hatchback</type>
                  <merk>Opel</merk>
                  <model>Minerva</model>
                  <bouwjaar>1999</bouwjaar>
                  <brandstof>Benzine</brandstof>
                  <prijs valuta="euro">2199</prijs>
                  <datumEindAPK>19-11-2018</datumEindAPK>
                  <fotos>
                      <foto>
                          <bestandsLocatie>http://www.garageschuurman.nl/fiatpanda.jpg</bestandsLocatie>
                          <alt>Onze Auto</alt>
                      </foto>
                  </fotos>
              </occasions>

              <!--Huur-->
              <huur uitleenbaar="false">
                  <kenteken>PP-UY-81</kenteken>
                  <type>Sedan</type>
                  <merk>Volkswagen</merk>
                  <model>Scirocco</model>
                  <bouwjaar>2004</bouwjaar>
                  <brandstof>Diesel</brandstof>
                  <prijs valuta="euro">100</prijs>
                  <datumEindAPK>07-09-2018</datumEindAPK>
                  <fotos>
                      <foto>
                          <bestandsLocatie>http://www.garageschuurman.nl/opelminerva.jpg</bestandsLocatie>
                          <alt>Onze Auto</alt>
                      </foto>
                  </fotos>
              </huur>
          </autos>

        </showroom>

				<!--Keurmerken-->
        <keurmerken>
            <keurmerk type="BOVAG"/>
        </keurmerken>

				<!--Medewerkers-->
        <medewerkers>
            <medewerker>
                <naam>Hessel Houtman</naam>
                <foto>
                    <bestandsLocatie>http://www.garageschuurman.nl/happyhessel.jpg</bestandsLocatie>
                    <alt>Onze Hessel</alt>
                </foto>
                <functie>Koffie faciliteur</functie>
            </medewerker>
        </medewerkers>
    </garage> <!-- garage 1 -->
    <garage naam="Garage De Vries"> <!-- garage 2 -->

        <!--Adres-->
        <adres>
            <straat>Veldweg</straat>
            <nummer>3</nummer>
            <postcode>7832AG</postcode>
            <plaats>Groningen</plaats>
            <provincie>Groningen</provincie>
        </adres>

        <!--ContactGegevens-->
        <contactGegevens>
            <telefoonnummer>0673927883</telefoonnummer>
            <email>info@garagedevries.nl</email>
            <website>http://www.devries-garage.nl</website>
            <omschrijving> Bert Visser beheert sinds 1985 garage De Vries.</omschrijving>
            <routebeschrijving> https://www.google.nl/maps/dir/''/garage+De+Vries/</routebeschrijving>
        </contactGegevens>

        <!--Faciliteiten-->
        <faciliteiten>
            <pompen>
                <pomp brandstofType="Diesel"/>
                <pomp brandstofType="Benzine"/>
                <pomp brandstofType="Benzine"/>
                <pomp brandstofType="Gas"/>
            </pompen>

            <wassen>
                <wasstraat aantal="2"/>
                <wasbox aantal="0"/>
            </wassen>
            <!--Winkel-->
            <winkel>

                <openingstijden>
                    <maandag open="8:00" sluiting="23:00"/>
                    <dinsdag open="8:00" sluiting="23:00"/>
                    <woensdag open="12:00" sluiting="23:00"/>
                    <donderdag open="9:00" sluiting="23:00"/>
                    <vrijdag open="9:00" sluiting="23:00"/>
                    <zaterdag open="9:00" sluiting="20:00"/>
                    <zondag open="-" sluiting="-"/>
                </openingstijden>

                <assortiment>
                    <rookwaar/>
                    <tijdschriften/>
                </assortiment>

            </winkel>
        </faciliteiten>

        <!--Foto's-->
        <fotos>
            <foto>
                <bestandsLocatie>http://www.devries-garage.nl/foto.jpg</bestandsLocatie>
                <alt>Foto van garage De Vries</alt>
            </foto>
        </fotos>

        <!--Werkplaats-->
        <werkplaats>

            <openingstijden>
                <maandag open="8:00" sluiting="18:00"/>
                <dinsdag open="8:00" sluiting="18:00"/>
                <woensdag open="8:00" sluiting="18:00"/>
                <donderdag open="8:00" sluiting="18:00"/>
                <vrijdag open="8:00" sluiting="15:00"/>
                <zaterdag open="8:00" sluiting="14:00"/>
                <zondag open="-" sluiting="-"/>
            </openingstijden>

            <werkzaamheden>
                <onderhoud/>
                <APKkeuring/>
                <schadeherstel/>
                <bandenservice/>
            </werkzaamheden>
        </werkplaats>

        <!--Showroom-->
        <showroom>

            <openingstijden>
                <maandag open="9:00" sluiting="17:00"/>
                <dinsdag open="9:00" sluiting="17:00"/>
                <woensdag open="9:00" sluiting="17:00"/>
                <donderdag open="9:00" sluiting="17:00"/>
                <vrijdag open="9:00" sluiting="17:00"/>
                <zaterdag open="9:00" sluiting="13:00"/>
                <zondag open="-" sluiting="-"/>
            </openingstijden>

            <autos>
                <!--Nieuw-->
                <nieuw>
                    <kenteken>AG-ER-33</kenteken>
                    <type>Hatchback</type>
                    <merk>Volkswagen</merk>
                    <model>Lupo</model>
                    <bouwjaar>1998</bouwjaar>
                    <brandstof>Benzine</brandstof>
                    <prijs valuta="euro">6000</prijs>
                    <datumEindAPK>13-03-2015</datumEindAPK>
                    <fotos>
                        <foto>
                            <bestandsLocatie>http://www.devries-garage.nl/65321.jpg</bestandsLocatie>
                            <alt>VW Lupo</alt>
                        </foto>
                    </fotos>
                </nieuw>
                <nieuw>
